### ISSUE TITLE
Need to use fetch() Swiggy's endpoint for live restaurants data

### ISSUE THREAD

**Issue by theprashasst** [Ankush11903/Foodsale#6]
I think instead of just copying the whole JSON file from Swiggy's endpoint you could have implemented fetching data from Swiggy's api and then using live data

https://github.com/Ankush11903/Foodsale/blob/a21269f237297921b83b35e58e3e35fa1fb060b6/src/Constants.jsx#L1-L2582

**Comment by Ankush11903** [comment]
I have used live data only but this thing is done long back when I don't have enough knowledge of backend and cors issue.
So,this was just alternative for downloading cors extension.
