### ISSUE TITLE
offset issue

### ISSUE THREAD

**Issue by suprajaboga** [Ankush11903/Foodsale#7]
These both urls are giving me same set of data..

https://www.swiggy.com/dapi/restaurants/list/v5?lat=28.6126255&lng=77.04108959999999&offset=1&sortBy=RELEVANCE&pageType=SEE_ALL&page_type=DESKTOP_SEE_ALL_LISTING

https://www.swiggy.com/dapi/restaurants/list/v5?lat=28.6126255&lng=77.04108959999999&offset=2&sortBy=RELEVANCE&pageType=SEE_ALL&page_type=DESKTOP_SEE_ALL_LISTING

I changed the value of offset only, but both urls are giving me same restaurants. Is there anything I need to change @Ankush11903 ?

**Comment by Ankush11903** [comment]
Change lat and lng values
